2020-09-02 16:29:15,329 ERROR: Exception on /hansard [GET] [in /Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michellewong/Documents/Speakup/app/routes.py", line 184, in hansard
    return render_template('hansard.html',data = hansard)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/michellewong/Documents/Speakup/app/templates/hansard.html", line 1, in top-level template code
    {% extends "navbar.html" %}
  File "/Users/michellewong/Documents/Speakup/app/templates/navbar.html", line 52, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/michellewong/Documents/Speakup/app/templates/hansard.html", line 80, in block "content"
    {%for speech in major_heading.minor_heading.speech.all()%}
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.MajorHeading object' has no attribute 'minor_heading'
2020-09-02 16:29:38,439 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:30:48,825 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:43:34,104 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:43:50,240 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:44:13,629 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:44:32,745 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:47:23,539 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:51:15,442 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:51:56,088 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:52:25,043 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:53:14,804 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:54:12,429 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 16:55:12,399 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:33:30,110 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:34:38,315 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:35:31,391 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:36:54,759 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:37:22,917 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:37:38,707 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:37:47,511 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:41:41,990 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:41:53,166 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:46:06,850 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:46:40,644 ERROR: Exception on /hansard [GET] [in /Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michellewong/Documents/Speakup/app/routes.py", line 184, in hansard
    return render_template('hansard.html',data = hansard)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/michellewong/Documents/Speakup/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/michellewong/Documents/Speakup/app/templates/hansard.html", line 95, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2020-09-02 17:47:01,376 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:47:26,931 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:56:15,165 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 17:56:52,203 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:07:17,221 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:08:31,767 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:10:01,079 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:10:35,785 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:12:09,520 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 18:16:06,250 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
2020-09-02 20:36:15,291 INFO: Microblog startup [in /Users/michellewong/Documents/Speakup/app/__init__.py:46]
